### ISSUE TITLE
Inferring on any instance in the kitti-raw dataset

### ISSUE THREAD

**Issue by lif314** [youmi-zym/CompletionFormer#11]
Thank you for your great work. I want to infer on any instance in the kitti-raw dataset, but the structure of kitti-raw and KITTI-DC is not consistent. That is to say, given a frame of raw image, raw lidar data and the relationship parameters between the two, can I directly obtain the completed result with the pretrained model? Can you give me some help, such as a script? thank you!

**Comment by lif314** [comment]
> {
> "rgb": "rawdata/2011_09_30/2011_09_30_drive_0028_sync/image_03/data/0000001643.png",
> "depth": "data_depth_velodyne/train/2011_09_30_drive_0028_sync/proj_depth/velodyne_raw/image_03/0000001643.png",
> "gt": "data_depth_annotated/train/2011_09_30_drive_0028_sync/proj_depth/groundtruth/image_03/0000001643.png",
> "K": "rawdata/2011_09_30/calib_cam_to_cam.txt"
> }

非常感谢您的回复！您的模型是在KITTI_DC数据集上训练和测试的，这个数据集提供了列表中的`depth`和`gt`。我现在想在KITTI上的其它数据集上使用您的预训练模型来进行推理，比如KITTI Odometry数据集，这个数据集只包含了rgb图像、原始点云数据以及一些转换参数。所以我想实现输入rgb图像和原始点云，将点云投影到图像平面上获取深度，然后直接接入您的预训练模型上进行推理，请问您可以帮忙吗？（因为我没有找到KITTI_DC中`depth`和`gt`的生成方式）非常感谢！

**Comment by youmi-zym** [comment]
Hi, 
Okay, I got your points. To project the 3D point cloud into depth image, maybe you can infer to [this](https://github.com/nianticlabs/monodepth2/blob/master/datasets/kitti_dataset.py#L70). I think it would help.

Best,

**Comment by lif314** [comment]
> 

Thanks a bunch!
