### ISSUE TITLE
About skip connection on model output

### ISSUE THREAD

**Issue by HencyChen** [youmi-zym/CompletionFormer#13]
Hi @mattpoggi and @youmi-zym,

Thanks for the great work!

The model architecture in paper Fig. 2, it seems the model output is directly a depth map, however, in src/model/completionformer.py line 31, the model output is added by the input sparse depth. 

I'm wondering if there's something I miss in the paper? Since in the code, the model seems to predict the residual depth but not a entire depth map.

Thanks!

**Comment by youmi-zym** [comment]
Hi,
Thanks for your interest! You're right, our model learns the residual and we didn't draw this in the Fig.2. 

Best,
Youmin

**Comment by BloodLemonS** [comment]
Hi, @youmi-zym 
I am very interested in this issue, 
but I did not understand what you mean about ‘learns the residual'. Can you explain it in detail?
