### ISSUE TITLE
Some important questions regarding Completion former

### ISSUE THREAD

**Issue by ArghyaChatterjee** [youmi-zym/CompletionFormer#14]
Hello, thanks for your work. I have some questions. Here are they:

1. When I am giving your model a try with kitti test dataset that you mentioned in the readme, without --save_result_only flag, I saw there are around 5-6 intermediate images with final predicted image and error bar calculated. Now I was trying to also save the gt.min() and gt.max() values and the gt.min() value is always 0 where gt.max() value is somewhere between 60.0-80.0 for different images. Now, I assume this value is basically uint16 bit where I have to multiply that with 256 to get the actual value which is somewhere around 15360.0-20480.0. 
          a. The question is uint16 bit depth image range is from 0 to 65535. Why is this stuck on values only between 0-20480.0 rather expanding it to 0-65535?
          b. You have set the max depth flag to 90.0 whereas for the kitti dataset, as long as I know, they are using HDL-64 which has a max depth of 200m and a minimum range of 2.0m. 
          c. In your code, are you using the minimum depth (~2m) of HDL-64 anywhere?Are you using minimum depth anywhere at all ?
          b. How to get distance from these uint values ? If I assume that minimum depth for the data that you are referring as kitti_test is 2m and maximum depth is 200m for each and every sample, then for a single sample, each depth pixel depth in meters, D = (200 - 2) / (20480 - 0) * B + 2, is that correct ?

2. Why do you need K matrix ? In your work, I can see you are feeding RGB image and RGB aligned depth image. Then, what's the necessity to use K matrix ?

3. I have provided a case below where I have to do bottom cropping but I see you are not doing that. I can see you are doing top cropping. Can you give an example for bottom cropping problem ?
          
![PXL_20230810_074156648~2](https://github.com/youmi-zym/CompletionFormer/assets/28845357/8f1950ef-9e7d-46ba-aff5-8528c6604200)

**Comment by ArghyaChatterjee** [comment]
@youmi-zym , if you are taking time to answer all of them at once, can you answer them part by part ? Specially no. 3 first. I need the answer early for the project ?

**Comment by youmi-zym** [comment]
Hi,

Sorry for the lateness. 

1) You can check [here](https://github.com/youmi-zym/CompletionFormer/blob/main/src/summary/cfsummary.py#L201) to take a view of how we save the results. For KITTI, we crop the distance within [0, 90]m.

2) You're right, the intrinsic matrix is not used. You can ignore it if necessary.

3) We crop on the top due to it belongs to the sky region. There is no valid LiDAR scans. Anyway, it's free for you to crop the bottom, I believe it impacts little.

Best,
Youmin
