### ISSUE TITLE
Inference Time

### ISSUE THREAD

**Issue by Sabo-99** [youmi-zym/CompletionFormer#15]
Hi! Thanks for your great work @youmi-zym :)
I have some questions about your experiment results.

1) In Table 4, the performance results of NLSPN are different from the original paper (ECCV'20). Can you tell me how you tested it and why it differs from the original paper results?

2) In Section 5 Conclusion and Limitations, you mentioned CompletionFormer runs at about 10 FPS. Is it a result of using 4 3090 GPUs?

**Comment by youmi-zym** [comment]
Hi @Sabo-99,

Thanks for your interest. 

1. We got the results in Tab.4 by rerunning the NLSPN with 1, 4, 16, and 64 lidar lines. I checked the original paper of NLSPN, their result with 64 lidar lines is 884.1mm (RMSE), which is very close to our test (889.4mm in RMSE) in Table 4.
2. The runtime is tested on one single 3090 GPUs. Only training needs more gpus.

Best,
Youmin
