### ISSUE TITLE
some error in kitti_dc.json file

### ISSUE THREAD

**Issue by Guzaiwang** [youmi-zym/CompletionFormer#17]
Thanks for your good work.

I am following data_preparing as illustrated in readme.md.

I note that there is "2011_09_28_drive_0016_sync" in the kitti_dc.json. 
![image](https://github.com/youmi-zym/CompletionFormer/assets/48231203/335ce1f8-14f8-4e57-b094-d59c7696b64b)

However, the dataset downloaded from [https://github.com/youmizym/CompletionFormer/files/11832324/kitti_archives_to_download.txt](url) does not contain this folder. 
![image](https://github.com/youmi-zym/CompletionFormer/assets/48231203/da9f46d1-2ee2-4e1e-9488-7f037a040a48)

It will cause some problems in the training. 

Coudl you help me to solve this problem?

**Comment by youmi-zym** [comment]
Hi,
Thanks for pointing out this. I have updated the script (https://github.com/youmi-zym/CompletionFormer/files/12575038/kitti_archives_to_download.txt) there accordingly. Thanks!

Best, 
Youmin
