### ISSUE TITLE
Regarding depth conventions and weird outputs

### ISSUE THREAD

**Issue by ayushjain1144** [youmi-zym/CompletionFormer#18]
Hi, 

Thank you for your awesome work! I am trying to run your model on scannet RGB-D images to do depth completion. The depth in scannet is in mm, so I am dividing my depth by 1000.0 to convert it in metres. Next, I used the pre-trained NYUv2 checkpoint to complete the depth but I am noticing the predicted depth residual `pred_init` to be pretty big -- between [0, 2.7931] while my input depth (in m) is between [0, 2]. Could you let me know what I am missing? Thank you so much!

The command I ran:
`python main.py --data_name scannet --test_only --log_dir /projects/katefgroup/language_grounding/completion_former/scannet \
--save_image --gpus 0 --pretrain /projects/katefgroup/language_grounding/NYUv2.pt`

I am attaching the `04_pred_prop_5.jpg` for your reference. 
<img width="231" alt="Screenshot 2023-09-21 at 1 53 14 PM" src="https://github.com/youmi-zym/CompletionFormer/assets/28894174/be91f612-6735-457c-9103-21836a6baa64">

**Comment by youmi-zym** [comment]
Hi,

It's quite weird. Given the provided details, it's hard to figure out the real problems. Maybe you can try with images from NYUv2 first, just to promise the issue is not raised by the dataloader, model, and other parts in the code. After that, you can inference with your images.

Best, 
Youmin

**Comment by ayushjain1144** [comment]
Thank you Youmin, turns out that I needed to fine-tune the NYUv2 checkpoint for a few epochs to get decent results. I suspect that maybe the model is trained with very sparse depth and thus when I am supplying it depth from Kinect sensor of scannet, it is out-of-distribution of the model.
