### ISSUE TITLE
How to solve this problem?AttributeError: 'numpy.ndarray' object has no attribute 'detach'

### ISSUE THREAD

**Issue by BloodLemonS** [youmi-zym/CompletionFormer#19]
Hello, I encountered the following issue while running. It should be a data issue between Tensor and Numpy. How can I modify this issue?
AttributeError: 'numpy.ndarray' object has no attribute 'detach'
![2023-10-11 20-13-00屏幕截图](https://github.com/youmi-zym/CompletionFormer/assets/56753880/5c26b1fd-4549-4c3a-b049-e11d7b742dd4)

**Comment by youmi-zym** [comment]
Hi,

I checked the code but didn't find any potential bug that could cause this problem. Could you print more information, such as the type, size, and mean value of each feature in output['pred_inter'], for debugging?

Best, 
Youmin

**Comment by BloodLemonS** [comment]
Hello, I have previously conducted a transformation of data to sth=torch. from_ The operation of numpy (sth) results in a change in the data dimension. If there is no change, an email submission issue will occur, and the output data dimension is shown in the image.





936627648
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youmi-zym/CompletionFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月24日(星期二) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youmi-zym/CompletionFormer] How to solve this problem?AttributeError: 'numpy.ndarray' object has no attribute 'detach' (Issue #19)





 
Hi,
 
I checked the code but didn't find any potential bug that could cause this problem. Could you print more information, such as the type, size, and mean value of each feature in output['pred_inter'], for debugging?
 
Best,
 Youmin

**Comment by youmi-zym** [comment]
Hi,

Sorry, I don't understand what you did, and I didn't see the shown image.

Best,
Youmin

**Comment by BloodLemonS** [comment]
/home/lemon/桌面/2023-10-24 16-55-14屏幕截图.png
/home/lemon/桌面/906630C368312DD229511A5E5F086618.jpg

**Comment by BloodLemonS** [comment]
![2023-10-24 16-55-14屏幕截图](https://github.com/youmi-zym/CompletionFormer/assets/56753880/88ff179b-d807-48e4-b2be-2e755cab7fb5)
![906630C368312DD229511A5E5F086618](https://github.com/youmi-zym/CompletionFormer/assets/56753880/d98a6514-9588-4858-aaae-37dea7b3fb03)

**Comment by BloodLemonS** [comment]
As shown in the picture, the main operation is to change the type of data. After the change, there was a change in the data dimension, which resulted in subsequent code not being able to run correctly

**Comment by BloodLemonS** [comment]
![2023-10-24 20-07-37屏幕截图](https://github.com/youmi-zym/CompletionFormer/assets/56753880/ad9de64d-72ba-4f68-a124-e5f05a49b5dd)
This is the result of my re-outputting the output, and I have not changed the content of the code

**Comment by youmi-zym** [comment]
Hi,

Can you add this in cfsummary.py at the file beginning:

`from copy import deepcopy
`

and then modify this [line](https://github.com/youmi-zym/CompletionFormer/blob/main/src/summary/cfsummary.py#L231) to:

`feat_inter = deepcopy(list_feat[k])
` 

I think it'd be fine after solving this bug.

Best,
Youmin

**Comment by BloodLemonS** [comment]
Hello, following your instructions, this bug still exists and has not been resolved.
![2023-10-24 21-53-11屏幕截图](https://github.com/youmi-zym/CompletionFormer/assets/56753880/894e4b5c-73a9-4ee7-a7ae-4deb033cc8aa)

**Comment by BloodLemonS** [comment]
The error reported should be on line 95 of the cfsummary.py file

**Comment by youmi-zym** [comment]
Hi, 

What if also change this [line](https://github.com/youmi-zym/CompletionFormer/blob/main/src/summary/cfsummary.py#L207) to:

`list_feat = deepcopy(output['pred_inter'])`

**Comment by BloodLemonS** [comment]
Although this issue did not occur, another issue arose.
![2023-10-24 22-25-16屏幕截图](https://github.com/youmi-zym/CompletionFormer/assets/56753880/0333ee9e-6a70-4f80-8d60-1801fa251b21)

**Comment by BloodLemonS** [comment]
The problem has been solved, thank you very much

**Comment by youmi-zym** [comment]
Great!
