### ISSUE TITLE
model without NLSPN

### ISSUE THREAD

**Issue by LingerWang** [youmi-zym/CompletionFormer#20]
Dear author:
    I am very appreciate for your work and very grateful for your sharing you code for us. I  encountered some issues while replicating your work and would like to seek your guidance.
    When I train the model without the NLSPN mudule, we found that the pred depth map is showing noticeable 'spots,' and upon observation, these points happen to be exactly where the original sparse points are located. Have you encountered this situation, or do you have any suggestions?
    Best wishes!

**Comment by LingerWang** [comment]
![图片](https://github.com/youmi-zym/CompletionFormer/assets/37800175/e2b9d329-146b-40d1-9b04-60a85171ddbf)
![图片](https://github.com/youmi-zym/CompletionFormer/assets/37800175/aaf00a1f-4bca-4c7e-9955-e22725caa324)

**Comment by youmi-zym** [comment]
Hi,

It's due to we added the initial prediction with the sparse depth input, please check here: https://github.com/youmi-zym/CompletionFormer/blob/main/src/model/completionformer.py#L32.
