### ISSUE TITLE
Where to get pre-trained resnet34 and PVT

### ISSUE THREAD

**Issue by Lizhuoling** [youmi-zym/CompletionFormer#23]
Congratulations to your great work. I find the code requires pre-trained ResNet34 and PVT checkpoints, which are not mentioned in the README. Where can I get these checkpoints?

**Comment by youmi-zym** [comment]
Hi, 

You can find the checkpoints here https://drive.google.com/drive/folders/1kr08caYQyDub22uONfUnZv9gOkWQaA6h?usp=sharing. 

Best,
Youmin
