### ISSUE TITLE
Some questions about the pretrained model for NYU dataset

### ISSUE THREAD

**Issue by dongjinmingDJM** [youmi-zym/CompletionFormer#26]
Hello , sorry to bother you again , I'm wondering the NYU pretrained model is for 500 samples? Or 200 samples?

**Comment by youmi-zym** [comment]
Hi,

The NYU pretrained model is for 500 samples.

Best,
Youmin

**Comment by dongjinmingDJM** [comment]
> Hi,
> 
> The NYU pretrained model is for 500 samples.
> 
> Best, Youmin

Thank you for your reply
