### ISSUE TITLE
Is it possible to use deform_conv2d and torch.cuda.amp in your code?

### ISSUE THREAD

**Issue by navid-mahmoudian** [youmi-zym/CompletionFormer#3]
Hello,

Thank you for providing this great code. I am wondering if your code can be easily modified to incorporate the following changes:

- Instead of using NVIDIA Apex, which has now been integrated into PyTorch [torch.amp](https://pytorch.org/docs/master/amp.html), can the code be easily transferred to use `torch.cuda.amp` for automatic mixed precision?

- The PyTorch implementation of [Deformable Convolution v2](https://pytorch.org/vision/main/generated/torchvision.ops.deform_conv2d.html#deform-conv2d) is available in `torchvision.ops.deform_conv2d`. How can I modify `modulated_deform_conv_func.py` to use this instead of the `DCN` module? Specifically, I see you are using `DCN.modulated_deform_conv_forward` and `DCN.modulated_deform_conv_backward` in the `forward` and backward` functions respectively. What changes do I need to make to use the new implementation?

**Comment by youmi-zym** [comment]
Hi,
Thanks for your interest in our work. I agree that incorporating Pytorch default operations would make the repo more friendly, at least for environment preparation. 

1. I think it's not so hard to replace NVIDIA Apex with torch.amp, and I guess it doesn't impact the performance so much.
2. Following NLSPN, we use the implementation of [Deformable Convolution v2](https://github.com/youmi-zym/CompletionFormer#deformable-convolution-v2-dcnv2). However, you can modify [here](https://github.com/youmi-zym/CompletionFormer/blob/main/src/model/nlspn_module.py#L151) and [here](https://github.com/youmi-zym/CompletionFormer/blob/main/src/model/nlspn_module.py#L122) to use Pytorch implementation. 

Bests,
