### ISSUE TITLE
How can I complete my depth map？

### ISSUE THREAD

**Issue by pgswag** [youmi-zym/CompletionFormer#30]
Hi，I want to complete my own depth map directly on your trained model, how can I do that？
Do I need to convert depth maps and aligned color maps to H5 files？
Looking forward to your reply very much！

**Comment by youmi-zym** [comment]
Hi,

I don't think so. You can follow the Kitti dataset manner to load your data. We don't have a constrain on image/depth format.

Best,
Youmin

**Comment by pgswag** [comment]
Does this mean that I can directly take depth and color maps as input in the form of numpy arrays?
Are you Chinese? If so, can we contact through wechat or qq?
Thank you very much for your reply

**Comment by youmi-zym** [comment]
Hi,

As you prefer, you can do it in any format you want.

Sure, you can contact me through WeChat: youmistar . (Message will be deleted in one hour).

Best,
Youmin

**Comment by pgswag** [comment]
Hi，
I have seen your reply, for your privacy, you can delete it now.
Best，
Pg

**Comment by DZtucker** [comment]
@pgswag 
Hey, just checking in to see if you've managed to implement the depth and color map input as numpy arrays. If you have, could you share the snippet of the code where you handle this? It would be super helpful.

Cheers!
