### ISSUE TITLE
KITTI Online Server Submission

### ISSUE THREAD

**Issue by dsshim0125** [youmi-zym/CompletionFormer#4]
Hi,

Thank you for your work!

I think that the code does not top crop the images during the inference for KITTI Online Server submission.

It means that the resolution during the evaluation for KITTI Online Server submission is different from during the training and evaluation on the validation set.

Does it still produce plausible performance? (I mean that why do not training the same resolution as the image resolution for KITTI Online Server Submission? Does it make different performance?)

Thanks!

**Comment by youmi-zym** [comment]
Hi,
Thanks for your interest!

The command to run inference for KITTI submission is denoted [here](https://github.com/youmi-zym/CompletionFormer#-testing):

```
$ cd THIS_PROJECT_ROOT/src
$ python main.py --dir_data PATH_TO_KITTI_DC --data_name KITTIDC --split_json ../data_json/kitti_dc_test.json \
    --patch_height 240 --patch_width 1216 --gpus 0 --max_depth 90.0 \
    --test_only --pretrain PATH_TO_WEIGHTS --save_image --save_result_only --save NAME_TO_SAVE
```

There is no 'top-crop' option. 

Besides, we couldn't train the network without an image crop due to the resolution limitation, i.e., the height and width should be divided by 32.

Best.

**Comment by dsshim0125** [comment]
Thanks for your reply!

If the input image should be divided by 32, how can I use input  images and sparse depth for KITTI Online server submission as their size is not divided by 32?

Do I have to naively resize it to be same as during training?

If so, how can I resize sparse depth as resize method changes the information whether this pixel is originally empty or the sparse depth value?
