### ISSUE TITLE
Having problems with kitti dataset evaluation

### ISSUE THREAD

**Issue by ArghyaChatterjee** [youmi-zym/CompletionFormer#8]
Hello, 
I was implementing your work on kitti dataset. As you have mentioned in your work that the kitti_raw directory should have the below structure:
```
|   |   ├── 2011_09_26
|   |   ├── 2011_09_28
|   |   ├── 2011_09_29
|   |   ├── 2011_09_30
|   |   ├── 2011_10_03
```
I can't see the kitti dataset like that. Inside the website, there are categories like: City, Residential, Road, Campus, Person, Calibration. Which one are you referring to ? Say inside city, there are sequences like 2011_09_26_drive_0001, ... and so on (26, 28, 29). Inside residential, there are (26, 30, 3); inside road (26, 29, 30, 03) and so on. Also, you didn't mention that do I have to download unsynced+unrectified dataset or synced+rectified dataset along with/without calibration file ??

Please clarify. Thanks in advance.

**Comment by youmi-zym** [comment]
Hi, 

Sorry for the trouble. You can use the following script to download the kitti raw dataset as listed in
[kitti_archives_to_download.txt](https://github.com/youmi-zym/CompletionFormer/files/11832324/kitti_archives_to_download.txt):


```

wget -i kitti_archives_to_download.txt -P kitti_raw/
cd kitti_raw
unzip "*.zip"

```
Warning: it weights about 175GB, make sure you have enough space to unzip too!

**Comment by ArghyaChatterjee** [comment]
Thanks for the clarification. Closing the issue.
