### ISSUE TITLE
About KITTI dataset evaluation and reporting

### ISSUE THREAD

**Issue by ArghyaChatterjee** [youmi-zym/CompletionFormer#9]
Hello,

I am trying to understand how do you go for the KITTI evaluation and reporting? 

1. Is it that, there are some ground truth depth images that you compare against (which are they)? Say your method predicted depth for 100 images from KITTI dataset, how do you compare against the ground truth depth images ? Where is the script for generating the RMSE, MAE, iRMSE and iMAE ? Is it generated by you or by KITTI themselves for you?

2. How do you report the depth to the website: https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion ? I mean how do you submit your work and who validates the evaluation matrics ? Is it you who report the evaluation metrics by yourself or is it them (KITTI) who do it for each and every new methods that come up ? Where and how do you submit the result as I didn't see any submission page?

Sorry, I am trying to go deeper so I need to know this process. Thanks in advance.

**Comment by ArghyaChatterjee** [comment]
Also, what's the range for the depth images in KITTI dataset ? I mean the closest distance in meters and the furthest distance in meters ?

**Comment by youmi-zym** [comment]
Hi,

You can find the evaluation script [here](https://github.com/youmi-zym/CompletionFormer/blob/main/src/metric/cfmetric.py). As for the benchmark, I suggest careful reading of the KITTI DC website. The depth range for KITTI is within [0.001, 90]m.

Best,
Youmin
